version: 2.1
jobs:
  backend:
    machine:
      image: ubuntu-2004:2023.10.1
    steps:
      - checkout
      - run:
          name: Build Backend
          command: |
            cd backend
            docker-compose build
      - run:
          name: Create/Migrate/Seed Database
          command: |
            cd backend
            docker-compose run backend rails db:create db:migrate db:seed
      - run:
          name: Run Backend API Server
          command: |
            cd backend
            docker-compose up -d
      
workflows:
  test:
    jobs:
      - backend
